name: Communicating with Catalyst

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, closed]
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled]
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited]
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  trigger_catalyst_function:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Call Zoho Catalyst Function
        uses: ./.github/actions/catalyst-function-call
        with:
          catalyst-function-url: ${{ secrets.CATALYST_FUNCTION_URL }}
          endpoint: ${{ secrets.ENDPOINT }}
          event-name: ${{ github.event_name }}
          event-action: ${{ github.event.action }}
          actor: ${{ github.actor }}
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          run-id: ${{ github.run_id }}
          pr-number: ${{ github.event.pull_request.number }}
          label-name: ${{ github.event.label.name }}
